Use redux in react component
shaaibu7/Bookstore-with-react pull request #3
Opened 2023-03-07 20:33 UTC by shaaibu7

- [ ] Implement redux store
- [ ] Implement state slice
- [ ] Display books, received from the slice, in a reusable component
- [ ] Dispatch actions using useDispatch
- [ ] Add event handlers for adding and removing books from the store

2023-03-07 21:26 UTC, Gambit142 requested changes
Hi @shaaibu7 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- Use of `configureStore` from @reduxjs/toolkit ✔️
- Use of `createSlice` from @reduxjs/toolkit ✔️
- Use of `react-redux` hooks ✔️

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-07 21:26 UTC, Gambit142 commented on src/redux/books/bookSlice.js
> +      };
- [ ] When I add a book, I get this error in the console 

![image](https://user-images.githubusercontent.com/77106962/223551448-1b09afd1-549f-4255-9307-b08c24f1ac58.png)

The reason why you have this error is that you have defined the `category` variable as compulsory in the redux slice but when you are using the `addBook` function in the component, you don't pass in any value for the `category`. It would be nice to remove this category variable until you need it. 👍 😎

2023-03-07 21:26 UTC, Gambit142 commented on src/redux/books/bookSlice.js
> +    },
- [ ] When you use the `push` method, you make the state mutable and it isn't a good practice in redux. There are several reasons why you should not mutate state in Redux: It causes bugs, such as the UI not updating properly to show the latest values. It makes it harder to understand why and how the state has been updated. It makes it harder to write tests. To make the state immutable, kindly do this: `state.bookList = [...state.bookList, newBook];` instead of `state.bookList.push(newBook);` 💻 😎

2023-03-07 21:26 UTC, Gambit142 commented on src/redux/categories/categoriesSlice.js
> +});
- [ ] In your `Categories` component, kindly dispatch the `checkStatus` function when the button is clicked. Remember that the UI should show the text `"Under Construction"` when the button is clicked. 👍

2023-03-07 21:26 UTC, Gambit142 commented on src/redux/categories/categoriesSlice.js
> +      }
- [ ] Kindly make the state immutable. Please refer to my comment  for this suggestion. 👍

2023-03-08 13:55 UTC, rloterh commented on src/redux/books/bookSlice.js
> +      };
resolved! ✔️

2023-03-08 13:59 UTC, rloterh commented on src/redux/categories/categoriesSlice.js
> +      }
resolved! ✔️

2023-03-08 13:59 UTC, rloterh commented on src/redux/categories/categoriesSlice.js
> +});
resolved! ✔️

2023-03-08 14:00 UTC, rloterh commented on src/redux/books/bookSlice.js
> +    },
resolved! ✔️

2023-03-08 14:02 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Suleiman,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
💠Redux state management properly applied to React components!
💠 ReadMe looks professional!

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 14:09 UTC, merged